# Generated by Django 5.0.4 on 2024-04-29 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_persondetail_address_alter_persondetail_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200, null=True)),
                ('Personid', models.CharField(max_length=200, null=True)),
                ('emailtype', models.CharField(choices=[('Home', 'Home'), ('college', 'college'), ('Office', 'Office')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(max_length=200, null=True)),
                ('Number', models.IntegerField(max_length=20, null=True)),
                ('Phonetype', models.CharField(choices=[('Home', 'Home'), ('Mobile', 'Mobile'), ('Office', 'Office')], max_length=200, null=True)),
            ],
        ),
    ]
