# Generated by Django 5.0.4 on 2024-04-29 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_phoneno_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneno',
            name='Number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='phoneno',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
