# Generated by Django 5.0.4 on 2024-04-29 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_phoneno_number_alter_phoneno_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='persondetail',
            name='email',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.email'),
        ),
        migrations.AddField(
            model_name='persondetail',
            name='phoneNO',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.phoneno'),
        ),
    ]
