# Generated by Django 5.0.4 on 2024-04-30 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_searchform_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='Address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='Name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
