# Generated by Django 5.0.4 on 2024-04-30 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_task_address_task_name_task_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persondetail',
            name='email',
        ),
        migrations.RemoveField(
            model_name='persondetail',
            name='phoneNO',
        ),
        migrations.AddField(
            model_name='persondetail',
            name='Email',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.email'),
        ),
        migrations.AddField(
            model_name='persondetail',
            name='PhoneNO',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.phoneno'),
        ),
    ]
