# Generated by Django 5.0.4 on 2024-04-30 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_remove_persondetail_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persondetail',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='persondetail',
            old_name='PhoneNO',
            new_name='phoneno',
        ),
    ]
