# Generated by Django 5.0.4 on 2024-05-01 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_rename_email_persondetail_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='Personid',
        ),
    ]
