# Generated by Django 5.0.4 on 2024-05-01 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_remove_email_personid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phoneno',
            name='user_id',
        ),
    ]
