# Generated by Django 5.0.4 on 2024-05-02 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_remove_phoneno_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='emailtype',
        ),
        migrations.RemoveField(
            model_name='persondetail',
            name='email',
        ),
        migrations.RemoveField(
            model_name='persondetail',
            name='phoneno',
        ),
        migrations.RemoveField(
            model_name='phoneno',
            name='Phonetype',
        ),
        migrations.AddField(
            model_name='email',
            name='persondetail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.persondetail'),
        ),
        migrations.AddField(
            model_name='phoneno',
            name='persondetail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.persondetail'),
        ),
    ]
