# Generated by Django 5.0.4 on 2024-05-02 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_remove_email_emailtype_remove_persondetail_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='persondetail',
        ),
        migrations.RemoveField(
            model_name='phoneno',
            name='persondetail',
        ),
        migrations.AddField(
            model_name='persondetail',
            name='email',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.email'),
        ),
        migrations.AddField(
            model_name='persondetail',
            name='phoneno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.phoneno'),
        ),
    ]
