# Generated by Django 5.0.4 on 2024-05-03 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_remove_email_persondetail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='emailtype',
            field=models.CharField(choices=[('Home', 'Home'), ('college', 'college'), ('Office', 'Office')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='phoneno',
            name='Phonetype',
            field=models.CharField(choices=[('Home', 'Home'), ('Mobile', 'Mobile'), ('Office', 'Office')], max_length=200, null=True),
        ),
    ]
